// Prompt Assist:多模态 Gemini 文本调用,给选中源图生成/改写一条图生视频运镜 promptBody。
// mock 优先(无 GEMINI_API_KEY 或 PROMPT_ASSIST_MOCK 时返回确定性 stub,开发态零花费,贴合“不浪费额度”)。
// 输出的是「正文」——房产保真护栏由 BFF 的 compileClipPrompt 事后置顶,这里只提示模型别越界,不重复整段护栏。
import { resolveImageInput } from './image-input';
import { envStr } from './env';
import type { FetchLike } from './types';

/* eslint-disable @typescript-eslint/no-explicit-any */

export type PromptAssistAction = 'generate' | 'improve';

export type PromptAssistInput = {
  imageUrl: string; // 绝对可达 URL(BFF 已解析)
  action: PromptAssistAction;
  currentPrompt?: string; // improve 时的现有正文
};

export type PromptAssistResult = {
  suggestedPrompt: string;
  rationale: string;
  warnings: string[];
  mock: boolean;
};

const MAX_PROMPT_CHARS = 1000;

export const clampPrompt = (s: string): string => String(s ?? '').replace(/\s+/g, ' ').trim().slice(0, MAX_PROMPT_CHARS);

// 正文级保真提醒(不含完整护栏 —— compileClipPrompt 会把 PROPERTY_FIDELITY_GUARDRAIL 置顶)。
const FIDELITY_NOTE =
  'The property must stay exactly as photographed: never invent, remove, remodel, restage, relight, or add architecture, furniture, decor, people, animals, vehicles, text, logos, or weather. Describe only a single continuous, restrained, physically plausible camera move over the visible scene.';

/** 组装喂给 Gemini 的文本指令(与图片一起走多模态)。 */
export const buildAssistInstruction = (action: PromptAssistAction, currentPrompt?: string): string => {
  const cur = clampPrompt(currentPrompt ?? '');
  const task =
    action === 'improve' && cur
      ? `Improve this existing real-estate image-to-video camera prompt while keeping its intent:\n"""${cur}"""`
      : 'Write a real-estate image-to-video camera prompt for this photo.';
  return [
    'You are a cinematographer writing image-to-video camera prompts for real-estate listing photos.',
    task,
    FIDELITY_NOTE,
    'Keep it concise (one or two sentences), concrete about the camera path, and grounded in what is visible in the photo.',
    `Respond with strict minified JSON only, no markdown, shaped exactly: {"suggestedPrompt": string, "rationale": string (one short sentence), "warnings": string[] (may be empty)}. suggestedPrompt must be at most ${MAX_PROMPT_CHARS} characters and contain only the camera-move body — no fidelity boilerplate.`,
  ].join('\n\n');
};

/** 无 key / mock 模式的确定性建议(不打真 Gemini)。 */
export const mockAssist = (action: PromptAssistAction, currentPrompt?: string): PromptAssistResult => {
  const cur = clampPrompt(currentPrompt ?? '');
  const base =
    action === 'improve' && cur
      ? `${cur} Keep the motion slow and continuous with stable exposure and straight architectural lines.`
      : 'Slow, steady push-in toward the main focal area of the room, holding straight architectural lines, natural light, and one continuous silent shot.';
  return {
    suggestedPrompt: clampPrompt(base),
    rationale: 'Offline mock suggestion (no GEMINI_API_KEY configured).',
    warnings: ['Generated by the offline mock — set GEMINI_API_KEY on the render server for real AI suggestions.'],
    mock: true,
  };
};

/** 从 Gemini responseMimeType:application/json 的返回里取正文文本(SDK 版本兼容:text 属性 / 函数 / candidates)。 */
export const extractResponseText = (response: any): string => {
  if (!response) return '';
  const t = response.text;
  if (typeof t === 'string') return t;
  if (typeof t === 'function') {
    try {
      return String(t.call(response) ?? '');
    } catch {
      /* fall through */
    }
  }
  const parts = response.candidates?.[0]?.content?.parts;
  if (Array.isArray(parts)) return parts.map((p: any) => p?.text ?? '').join('');
  return '';
};

/** 解析 Gemini 返回的 JSON(防御式:去代码围栏、字段兜底、正文夹紧、warnings 归一为 string[])。 */
export const parseAssistResponse = (text: string): PromptAssistResult => {
  const cleaned = String(text ?? '')
    .replace(/^\s*```(?:json)?/i, '')
    .replace(/```\s*$/i, '')
    .trim();
  let obj: any;
  try {
    obj = JSON.parse(cleaned);
  } catch {
    throw new Error('Prompt assist: model did not return valid JSON');
  }
  const suggestedPrompt = clampPrompt(obj?.suggestedPrompt ?? '');
  if (!suggestedPrompt) throw new Error('Prompt assist: response missing suggestedPrompt');
  const warnings = Array.isArray(obj?.warnings)
    ? obj.warnings.map((w: unknown) => String(w)).filter(Boolean).slice(0, 10)
    : [];
  return { suggestedPrompt, rationale: String(obj?.rationale ?? ''), warnings, mock: false };
};

/** 主入口:mock 优先;有 key 则取图字节 + 多模态 generateContent → 解析 JSON。 */
export const generatePromptAssist = async (
  input: PromptAssistInput,
  fetchImpl: FetchLike = ((...a: Parameters<typeof fetch>) => globalThis.fetch(...a)) as FetchLike,
): Promise<PromptAssistResult> => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || process.env.PROMPT_ASSIST_MOCK) return mockAssist(input.action, input.currentPrompt);

  const image = await resolveImageInput(input.imageUrl, 'base64', fetchImpl);
  const { GoogleGenAI } = await import('@google/genai');
  const ai: any = new GoogleGenAI({ apiKey });
  const model = envStr('PROMPT_ASSIST_MODEL', 'gemini-2.5-flash');
  const response = await ai.models.generateContent({
    model,
    contents: [
      {
        parts: [
          { inlineData: { mimeType: image.mimeType, data: image.base64 } },
          { text: buildAssistInstruction(input.action, input.currentPrompt) },
        ],
      },
    ],
    config: { responseMimeType: 'application/json', temperature: 0.7 },
  });
  return parseAssistResponse(extractResponseText(response));
};
